---
title: "Case Study 2"
author: "Brady Arendale"
date: "April 11, 2019"
output: 
  html_document:
    keep_md: true
---
# T-test
```{r}
# Read in data
workers <- read.csv("CaseStudy2-data.csv")
names(workers)[1] <- "Age"
workers2 <- workers
# Create dummy variables
businesstravel <- model.matrix(~0+BusinessTravel, data = workers)
department <- model.matrix(~0+Department, data = workers)
educationfield <- model.matrix(~0+EducationField, data = workers)
gender <- model.matrix(~0+Gender, data = workers)
jobrole <- model.matrix(~0+JobRole, data = workers)
maritalstatus <- model.matrix(~0+MaritalStatus, data = workers)
overtime <- model.matrix(~0+OverTime, data = workers)
# Add dummy variables to data frame
workers <- data.frame(workers, businesstravel, department, educationfield, gender, jobrole, maritalstatus, overtime)
# Run t-test for each variable on attrition
workers <- workers[,-c(3, 5, 8, 9, 10, 12, 16, 18, 22, 23, 27)]
for (i in 1:52) {
  print(names(workers)[i])
  if(class(workers[,i]) != "factor") {
    print(t.test(workers[,i] ~ Attrition, data = workers))
  } else {
    print("factor")
  }
}
```

# Logistic regression model
```{r}
model.full <- glm(Attrition ~ ., data = workers, family = binomial)
model.step <- step(model.full)
summary(model.step)
```

# Top three contributors?
```{r}
workers <- workers2
# Overall three biggest contributors to attrition
lm.null <- glm(Attrition ~ 1, data = workers, family = binomial)
add1(lm.null, ~Age + BusinessTravel + DailyRate + Department + DistanceFromHome + Education + EnvironmentSatisfaction + Gender + HourlyRate + JobInvolvement + JobLevel + JobRole + JobSatisfaction + MaritalStatus + MonthlyIncome + MonthlyRate + NumCompaniesWorked + OverTime + PercentSalaryHike + PerformanceRating + RelationshipSatisfaction + StockOptionLevel + TotalWorkingYears + TrainingTimesLastYear + WorkLifeBalance + YearsAtCompany + YearsInCurrentRole + YearsSinceLastPromotion + YearsWithCurrManager, test = "LRT")
add1(update(lm.null, ~ . + OverTime), ~Age + BusinessTravel + DailyRate + Department + DistanceFromHome + Education + EnvironmentSatisfaction + Gender + HourlyRate + JobInvolvement + JobLevel + JobRole + JobSatisfaction + MaritalStatus + MonthlyIncome + MonthlyRate + NumCompaniesWorked + OverTime + PercentSalaryHike + PerformanceRating + RelationshipSatisfaction + StockOptionLevel + TotalWorkingYears + TrainingTimesLastYear + WorkLifeBalance + YearsAtCompany + YearsInCurrentRole + YearsSinceLastPromotion + YearsWithCurrManager, test = "LRT")
add1(update(lm.null, ~ . + OverTime + JobRole), ~Age + BusinessTravel + DailyRate + Department + DistanceFromHome + Education + EnvironmentSatisfaction + Gender + HourlyRate + JobInvolvement + JobLevel + JobRole + JobSatisfaction + MaritalStatus + MonthlyIncome + MonthlyRate + NumCompaniesWorked + OverTime + PercentSalaryHike + PerformanceRating + RelationshipSatisfaction + StockOptionLevel + TotalWorkingYears + TrainingTimesLastYear + WorkLifeBalance + YearsAtCompany + YearsInCurrentRole + YearsSinceLastPromotion + YearsWithCurrManager, test = "LRT")
model.final <- update(lm.null, ~ . + OverTime + JobRole + MaritalStatus)
summary(model.final)

# We can't discriminate against age, gender, or marital status, so let's control for those variables
lm.base <- glm(Attrition ~ Age + Gender + MaritalStatus, data = workers, family = binomial)
add1(lm.base, ~Age + BusinessTravel + DailyRate + Department + DistanceFromHome + Education + EnvironmentSatisfaction + Gender + HourlyRate + JobInvolvement + JobLevel + JobRole + JobSatisfaction + MaritalStatus + MonthlyIncome + MonthlyRate + NumCompaniesWorked + OverTime + PercentSalaryHike + PerformanceRating + RelationshipSatisfaction + StockOptionLevel + TotalWorkingYears + TrainingTimesLastYear + WorkLifeBalance + YearsAtCompany + YearsInCurrentRole + YearsSinceLastPromotion + YearsWithCurrManager, test = "LRT")
add1(update(lm.base, ~ . + OverTime), ~Age + BusinessTravel + DailyRate + Department + DistanceFromHome + Education + EnvironmentSatisfaction + Gender + HourlyRate + JobInvolvement + JobLevel + JobRole + JobSatisfaction + MaritalStatus + MonthlyIncome + MonthlyRate + NumCompaniesWorked + OverTime + PercentSalaryHike + PerformanceRating + RelationshipSatisfaction + StockOptionLevel + TotalWorkingYears + TrainingTimesLastYear + WorkLifeBalance + YearsAtCompany + YearsInCurrentRole + YearsSinceLastPromotion + YearsWithCurrManager, test = "LRT")
add1(update(lm.base, ~ . + OverTime + JobRole), ~Age + BusinessTravel + DailyRate + Department + DistanceFromHome + Education + EnvironmentSatisfaction + Gender + HourlyRate + JobInvolvement + JobLevel + JobRole + JobSatisfaction + MaritalStatus + MonthlyIncome + MonthlyRate + NumCompaniesWorked + OverTime + PercentSalaryHike + PerformanceRating + RelationshipSatisfaction + StockOptionLevel + TotalWorkingYears + TrainingTimesLastYear + WorkLifeBalance + YearsAtCompany + YearsInCurrentRole + YearsSinceLastPromotion + YearsWithCurrManager, test = "LRT")
model.final.2 <- update(lm.base, ~ . + OverTime + JobRole + EnvironmentSatisfaction)
summary(model.final.2)
```