---
title: "CaseStudy02"
author: "Team ..."
date: "April 7, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## CASE STUDY 02 Plot Analysis
```{r warning=FALSE}
library(openxlsx)
library(MASS)
library(ggplot2)
library(classInt)
library(hexbin)
attritionData <- read.xlsx("CaseStudy2-data.xlsx")

# recode variables
attritionData$YesTotal <- length(attritionData$Attrition[as.character(attritionData$Attrition) == "Yes"]) # 237
attritionData$NoTotal <- length(attritionData$Attrition[as.character(attritionData$Attrition) == "No"]) # 1233
attritionData$Attrition <- factor(attritionData$Attrition)
attritionData$Gender <- as.factor(attritionData$Gender)
attritionData$Age <- as.integer(attritionData$Age)
attritionData$JobRole <- as.factor(attritionData$JobRole)
attritionData$Education <- as.factor(attritionData$Education)
attritionData$BusinessTravel <- as.factor(attritionData$BusinessTravel)
attritionData$Department <- as.factor(attritionData$Department)
attritionData$EducationField <- as.factor(attritionData$EducationField)
attritionData$Gender <- as.factor(attritionData$Gender)
attritionData$MaritalStatus <- as.factor(attritionData$MaritalStatus)
attritionData$Over18 <- as.factor(attritionData$Over18)
attritionData$OverTime <- as.factor(attritionData$OverTime)
attritionData$MaritalStatus <- as.factor(attritionData$MaritalStatus)
attritionData$MaritalStatus <- as.factor(attritionData$MaritalStatus)
attritionData$MaritalStatus <- as.factor(attritionData$MaritalStatus)
attritionData$AgeGroups <- cut(attritionData$Age, breaks=c(10,20,30,40,50,60))
attritionData$MonthlyIncomeGroup <-cut(attritionData$MonthlyIncome, 
                                       breaks=data.frame(
                                         classIntervals(
                                           attritionData$MonthlyIncome, n=5,
                                           method="quantile")[2])[,1],
                                         include.lowest=T,dig.lab=10)

# derive annual income and classify into income group based on quantiles 367/368 group
attritionData$YearlyIncome <- attritionData$MonthlyIncome*12
attritionData$YearlyIncomeGroup <- cut(attritionData$YearlyIncome, 
                                       breaks=data.frame(
                                           classIntervals(
                                               attritionData$YearlyIncome, n=4,
                                               method="quantile")[2])[,1],
                                       include.lowest=T,dig.lab=10, labels = c('lower','lower-middle','upper-middle','upper'))


attritionFemaleData <- as.data.frame(attritionData[as.character(attritionData$Gender) == "Female",])
attritionData$FemaleTotal <- length(attritionFemaleData)
attritionMaleData <- as.data.frame(attritionData[as.character(attritionData$Gender) == "Male",])
attritionData$MaleTotal <- length(attritionMaleData)
attritionData$YesFemaleTotal <- length(attritionData$Attrition[as.character(attritionData$Attrition) == "Yes" & as.character(attritionData$Gender) == "Female"]) 
attritionData$YesMaleTotal <- length(attritionData$Attrition[as.character(attritionData$Attrition) == "Yes" & as.character(attritionData$Gender) == "Male"])
```
## Generate Linear model and check assumptions
```{r warning=FALSE}
# generate linear model and run stepwise-selection model method
lm.full <- glm(Attrition ~ DistanceFromHome + Age + MonthlyIncome + Education + HourlyRate + HourlyRate + MonthlyIncome + PerformanceRating + WorkLifeBalance + 
                    JobLevel + NumCompaniesWorked + YearsInCurrentRole + YearsInCurrentRole + YearlyIncomeGroup + DailyRate + JobRole + StockOptionLevel + 
                    YearsSinceLastPromotion + Department + EnvironmentSatisfaction, data = attritionData, family = binomial)
lm.null <- glm(Attrition ~ 1, data = attritionData, family = binomial)

model.aic.stepwise <- step(lm.null, direction="both", trace=1, scope = ~ DistanceFromHome + Age + MonthlyIncome + Education + HourlyRate + HourlyRate + MonthlyIncome +
                             PerformanceRating + WorkLifeBalance + JobLevel + NumCompaniesWorked + YearsInCurrentRole + YearsInCurrentRole + YearlyIncomeGroup + DailyRate +
                             JobRole + StockOptionLevel + YearsSinceLastPromotion + Department + EnvironmentSatisfaction, data = attritionData, family = binomial)


# create scatter plot based model selection results
pairs(~Attrition+JobRole+StockOptionLevel+EnvironmentSatisfaction,
      data=attritionData, main="Stepwise Variable Selection Matrix")

pairs(~Attrition+JobRole+StockOptionLevel+ YearlyIncomeGroup + EnvironmentSatisfaction + DistanceFromHome + 
        NumCompaniesWorked + Age + YearsInCurrentRole + YearsSinceLastPromotion + WorkLifeBalance + DailyRate,
      data=attritionData, main="Stepwise Variable Selection Matrix")
```
## Generate Plots with top attributes
```{r warning=FALSE}
# show histograms of attrition based on different categories
ggplot(attritionData,aes(JobRole,fill=Attrition))+
    geom_histogram(color="black", stat="count", position="dodge")+
    labs(title="Job Role Attrition Histogram Plot",x="Job Role", y = "Frequency") +
    theme(panel.background = element_rect(fill = "#FDF8E2"),
          axis.text.x = element_text(angle = 90, hjust = 1),
          plot.title = element_text(hjust = 0.5))

ggplot(attritionData,aes(StockOptionLevel,fill=Attrition))+
    geom_histogram(color="black", stat="count", position="dodge")+
    labs(title="Stock Option Level Attrition Histogram Plot",x="Stock Option Level", y = "Frequency") +
    theme(panel.background = element_rect(fill = "#FDF8E2"),
          axis.text.x = element_text(angle = 90, hjust = 1),
          plot.title = element_text(hjust = 0.5))

attritionData$EnvironmentSatisfaction <- factor(attritionData$EnvironmentSatisfaction,                                    
                                                labels=c("Low","Medium","High","Very High"))
ggplot(attritionData,aes(EnvironmentSatisfaction,fill=Attrition))+
    geom_histogram(color="black", stat="count", position="dodge")+
    labs(title="Environment Satisfaction Attrition Histogram Plot",x="Environment Satisfaction", y = "Frequency") +
    theme(panel.background = element_rect(fill = "#FDF8E2"),
          axis.text.x = element_text(angle = 90, hjust = 1),
          plot.title = element_text(hjust = 0.5))

ggplot(attritionData,aes(YearsSinceLastPromotion,fill=Attrition))+
    geom_histogram(color="black", stat="count", position="dodge")+
    labs(title="Years Since Last Promotion Attrition Histogram Plot",
         x="Years Since Last Promotion", y = "Frequency") +
    theme(panel.background = element_rect(fill = "#FDF8E2"),
          axis.text.x = element_text(angle = 90, hjust = 1),
          plot.title = element_text(hjust = 0.5)) +
    coord_cartesian(ylim=c(0, 150))

ggplot(attritionData,aes(NumCompaniesWorked,Age, fill=Attrition))+
    geom_point(stat="identity", aes(col=Attrition), size=5)+
    labs(title="Age by Number of Companies Worked Plot",x="Number of Companies Worked", y = "Age")+
    theme(panel.background = element_rect(fill = "#FDF8E2"),
          plot.title = element_text(hjust = 0.5))

ggplot(attritionData,aes(YearlyIncomeGroup, fill=Attrition))+
    geom_histogram(color="black", stat="count")+
    labs(title="Yearly Income Group Attrition Histogram by Job Role Plot",
         x="Yearly Income Group", y = "Frequency") +
    theme(panel.background = element_rect(fill = "#FDF8E2"),
          axis.text.x = element_text(angle = 90, hjust = 1),
          plot.title = element_text(hjust = 0.5))+
    facet_grid(. ~ JobRole)

attritionData$WorkLifeBalance <- factor(attritionData$WorkLifeBalance, labels=c("Bad","Good","Better","Best"))
ggplot(attritionData,aes(YearsSinceLastPromotion,fill=Attrition))+
    geom_histogram(color="black", stat="count", position="dodge")+
    labs(title="Years Since Last Promotion by Work Life Balance Attrition Histogram Plot",
         x="Years Since Last Promotion", y = "Frequency") +
    theme(panel.background = element_rect(fill = "#FDF8E2"),
          axis.text.x = element_text(angle = 90, hjust = 1),
          plot.title = element_text(hjust = 0.5)) + 
    facet_grid(. ~ WorkLifeBalance)+
    coord_cartesian(ylim=c(0, 75))
    
# heat maps
hexbinplot(DistanceFromHome ~ Age | Attrition, attritionData,
           xlab="Age", ylab="Distance From Home", 
           main="Distance From Home by Age")

hexbinplot(JobLevel ~ MonthlyIncome | Attrition, attritionData,
           ylab="Job Level", xlab="Monthly Income",
           main="Job Level by Monthly Income")

hexbinplot(MonthlyIncome ~ Age | Attrition, attritionData,
           ylab="Monthly Income", xlab="Age",
           main="Monthly Income by Age")

# Look at Attrition and Gender
ggplot(attritionFemaleData, aes(x=Attrition, main="Female Attrition Histogram")) + 
  geom_histogram(color="black", fill="lightpink", stat="count")+
labs(title="Female Attrition Histogram Plot",x="Did they leave?", y = "Frequency")

ggplot(attritionMaleData, aes(x=Attrition, main="Male Attrition Histogram")) + 
  geom_histogram(color="black", fill="lightblue", stat="count")+
labs(title="Male Attrition Histogram Plot",x="Did they leave?", y = "Frequency")

# ~15% women leaving company
length(attritionFemaleData$Attrition[attritionFemaleData$Attrition == "Yes"]) / length(attritionFemaleData$Attrition)
length(attritionFemaleData$Attrition[attritionFemaleData$Attrition == "No"]) / length(attritionFemaleData$Attrition)

# ~17% men leaving company
length(attritionMaleData$Attrition[attritionMaleData$Attrition == "Yes"]) / length(attritionMaleData$Attrition)
length(attritionMaleData$Attrition[attritionMaleData$Attrition == "No"]) / length(attritionMaleData$Attrition)
```